name: SimpleChatPlus
version: '1.0b48'
main: net.antwan.simplechat.Main
author: Atsura
description: SimpleChat+ is a easy to use plugin based on chat moderation, management and filtering.
commands:
  chat:
    description: Main command of the plugin, type the /<scp help> for more infos.
    permission: scp.chat
    aliases:
      - scp
  banword:
    description: Banword manager command
    permission: scp.banword
    aliases:
      - bw